### PR TITLE
Add name normalization in tail optimization code

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Should fix https://github.com/elm-lang/error-message-catalog/issues/77 and https://github.com/elm-lang/elm-compiler/issues/1226, and let test case https://github.com/elm-lang/elm-compiler/pull/1250 succeed.

### CODE REVIEW

**Comment by laszlopandy** [comment]
Please merge your test case with this PR. Then we can see if your fix works (by the green "All checks have passed" that github shows).

**Comment by jvoigtlaender** [comment]
All green now, so the bug is indeed fixed, by this PR. Can be merged. @evancz

**Comment by mgold** [comment]
:+1:

**Comment by laszlopandy** [comment]
:smile: Thanks.
In the future, you can use `git rebase -i` with `fixup` to squish all your commits together. Then when your PR is merged into master it comes in as one clear commit.

**Comment by jvoigtlaender** [comment]
I know about `git rebase`. And I can not only do it in the future, I can also do it now. :smile:

Right? Or will force-pushing now somehow interact badly with the above merge commit?

**Comment by mgold** [comment]
You can always try it and see if the squashed commit has two parents. If not, replace your local copy with upstream, and try again.

**Comment by laszlopandy** [comment]
I often force push to PR branches and I have had no problems as long as no
one else is using my branch.

**Comment by evancz** [comment]
LGTM, thank you! :D

**Pull request merged**
