### PR TITLE
Improved parse error messages

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Previously, e.g., on a parse error for a record label, the parser would complain it expected a `lower case variable`, which might confuse the programmer. (Why is a record label a "variable"? It should be a "name".) Similarly, in the parse error for `case ... of Module.lowercasename -> ...` the parser would complain it expected an `upper case variable`, which again is confusing (see https://github.com/elm-lang/elm-compiler/issues/948). Instead, it would make more sense to complain that an `upper case name` was expected (a constructor is not a "variable", but it is a "name").

### CODE REVIEW

**Comment by evancz** [comment]
Can you share some cases where it actually *is* a variable? Is it an acceptable degradation of those messages to improve these cases? In practice, are the errors mentioned here more likely than ones that actually would be related to variables?

**Comment by evancz** [comment]
Also, let's add some cases to https://github.com/evancz/error-message-catalog to cover these situations.

**Comment by jvoigtlaender** [comment]
It's difficult for me to provide such cases, because I am not sure what other people consider to be "variables". For example, in this code:
```elm
f x = 10
```
are `f` and `x` "variables", or is only `x` a "variable"? I think I have seen both: people calling `f` a (top-level) variable as well, and people calling `f` a function and only `x` a variable.

**Comment by jvoigtlaender** [comment]
Okay, here is a case in which I managed to trigger the "expected lower case variable" error:
```elm
port Z : Int
port z = 5
```
This currently gives the message `unexpected "Z"; expecting whitespace, a newline or lower case variable`. Is `z`/`Z` really a "variable" here? Wouldn't this message also read better as `unexpected "Z"; expecting whitespace, a newline or lower case name`?

**Comment by mgold** [comment]
Yup, that's definitely not a variable. My first thought was "identifier" but "name" is certainly friendlier. So +1.

**Comment by jvoigtlaender** [comment]
Here is another case:
```elm
import Graphics.Element exposing (0)
```
currently gives the error message `expecting whitespace, a newline or listing of values (x,y,z)`. Here I would say that "values" is really wrong. What we expect there are "names". Because we could also list types there, not just functions and constants. But we don't consider types to be values.

**Comment by jvoigtlaender** [comment]
Sorry, that revert was accidental.

**Comment by jvoigtlaender** [comment]
In
```elm
type u a = Z
```
the error message currently is: `expecting whitespace, a newline, "alias" or upper case variable`. Again, "name" would make more sense to me than "variable", since the `U` in
```elm
type U a = Z
```
is not a variable.

I realize that all this does little to answer your question Evan, how the quality of error messages would be with "name" if the thing referred to by that name is *really* a variable. The problem is, I have problems triggering such errors. Because it seems that in situations where such an error could occur, actual errors are preempted by other messages. For example, if I make a mistake like writing ``4 `Basics.Min` 6`` instead of ``4 `Basics.min` 6``, where the `expected lower case variable` error could occur (because of accidental `Min` instead of `min`), what instead happens is that the error is `expecting whitespace or end of input` (because the `Min` was interpreted as a potential module qualifier). Similar in other situations.

So most of the evidence I can provide are only cases where using "name" instead of "variable" or "value" is more appropriate. And I can only hypothesize that in cases where the thing referred to is indeed something one would take to be a "variable", at least it wouldn't be too harmful to say "name" in the error message.

**Comment by jvoigtlaender** [comment]
I've added the cases from the above comments to https://github.com/evancz/error-message-catalog.

**Comment by evancz** [comment]
Great, thank you for showing these examples, this seems a lot nicer! And it seems like it's strictly an improvement, great find!

**Pull request merged**
