### PR TITLE
Setup issue template

### PR DESCRIPTION
**Pull request by evancz**
Thanks to @mgold for the helpful text!

### CODE REVIEW

**Comment by evancz** [comment]
Gah, it's trying to build with GHC 8 :(

Does @mgold or someone know a way to make it use GHC 7.10.2 like in my development environment? I know there's a PR about "fixing" this, but it's not clear if things keep working with 7.10.2.

**Comment by mgold** [comment]
Oh no! I'm thrilled that you're going to merge this though and +1 for the `.github` directory.

**Comment by jvoigtlaender** [comment]
What makes you think that GHC 8 is getting used? The Travis logs look to me like GHC 7.10 is getting used.

If you ask me, the problem is that no version bounds for `aeson-pretty` are currently specified in the `.cabal` file. As a consequence, a too new version of that library gets used. Namely one that has [this change](http://hdiff.luite.com/cgit/aeson-pretty/commit?id=0.8.0) to the type of the field `confIndent` of record type `Config`.

Constrain `aeson-pretty` to a version `< 0.8` and everything should be just fine.

**Comment by evancz** [comment]
@jvoigtlaender, do a PR!

**Comment by evancz** [comment]
Finally! Sheesh! Thanks @mgold and @jvoigtlaender for getting this going!

**Comment by mgold** [comment]
🎉 👏 🎉

**Pull request merged**
