### PR TITLE
Tests for #520: cannot access field of qualified record 

### LINKED ISSUE #520: cannot access field of qualified record (Graphics.Collage.defaultLine.color)
Syntax like `Graphics.Collage.defaultLine.color` won't compile; you instead have to write `.color Graphics.Collage.defaultLine`, which is clunky. Since modules are always upper-case and variables are always lower-case (and data constructors don't have fields), I don't think there's any ambiguity. Has this been discussed before?

### PR DESCRIPTION
**Pull request by jdudek**
Here’s another test—for PR #1170 (which fixes #520).

### CODE REVIEW

**Comment by AppSynergy** [comment]
Would love for this to go in!

**Comment by jvoigtlaender** [comment]
There seem to be merge conflicts here.

**Comment by jdudek** [comment]
Thanks! I’ll try to merge it with current master today evening UTC.

**Comment by evancz** [comment]
Will add tests when the underlying fix is made. Rather not do it through PR until then.

**Pull request closed without merging**
