### PR TITLE
Top level qualify

### PR DESCRIPTION
**Pull request by JoeyEremondi**
Introduces a new variant of `AST.Variable.Canonical`, namely `TopLevel`, which adds a module name to top-level local definitions.

This paves the road for lifting all outputted declarations to the top level.

For testing, I've ensured that this successfully builds several packages, including all of core. Additionally, JS output is unchanged for the entire Benchmark suite.

### CODE REVIEW

**Comment by evancz** [comment]
This is looking good! Surprisingly minor changes. I'm gonna try to merge it in soon.

**Comment by evancz** [comment]
Okay, I realized what was weird with the `[v1, v2]` part, and it just was something that surprised me in the existing code.

I had imagined that when you defined a variable in some pattern, it would take over everything. The imported things or built in things, none of that would be accessible in the environment anymore. Once it has been shadowed, it is not available anymore.

I guess I implemented it in a freaky way, and it happens to also work. I don't know if I knew I was doing this freaky thing when I did it.

In any case, that is why I was surprised by the `[v1,v2]` part. My mental model did not match the actual code.

That said, I think there is still a bug there. If a `Local` and a `TopLevel` are available, the `Local` should always win. I kinda want to just fix the underlying weirdness, so let me look into this a bit more for now.

**Comment by JoeyEremondi** [comment]
>
> If a Local and a TopLevel are available, the Local should always win.


That's the whole point of the [v1, v2]. It checks if both a local and a
top-level are in the environment, and prefers the local one.

**Comment by evancz** [comment]
Ah, I read read the body wrong, gotcha!

**Pull request merged**
