### PR TITLE
Add bad case for bug in type definitions

### PR DESCRIPTION
**Pull request by deadfoxygrandpa**
Addresses issue #1200, this file should not compile.

### CODE REVIEW

**Comment by mgold** [comment]
Wow, this actually does fail - I assumed it would have errored with "B is not in scope". When verifying a potential fix, you have to make sure it fails for the right reason!

**Comment by deadfoxygrandpa** [comment]
Are you sure? I think it fails because it's not supposed to compile, but it does compile. At least, that's how I'm reading this:
```
  Bad Tests:

    tests/test-files/bad/DotInType.elm: [Failed]

Compilation succeeded but should have failed

    tests/test-files/bad/IncompletePatternMatch.elm: [OK]

    tests/test-files/bad/InfiniteType.elm: [OK]

    tests/test-files/bad/NonElementMain.elm: [OK]

    tests/test-files/bad/Strings/ExtraClose.elm: [OK]
```
Maybe the output is confusing, because it looks like it's saying all of the "bad" tests except the new one I just added actually compile. But all of these tests were correct in all the other recent builds, I think?

**Comment by mgold** [comment]
> I think it fails because it's not supposed to compile, but it does compile.

Exactly. I typed the test into the REPL and got a JS error, so it compiled (but it shouldn't have). My concern is that I expected the compiler to reject the program because B was not defined, but if we imported B, the bug could still exist.

**Comment by ashnur** [comment]
I found this error while tried to define a type like this:
```
type KeyCode = Char.KeyCode
```
because I had some issues after updating to 0.16, and I was also very tired so I did the worst thing, just guessed something, then it compiled (before there was a compiler error regarding KeyCode not being present). Then I tried to look at it in the browser and it failed.

**Comment by jvoigtlaender** [comment]
Can this test case be merged, to hopefully facilitate fixing bug https://github.com/elm-lang/elm-compiler/issues/1200 sooner?

**Comment by evancz** [comment]
I'd rather track this as an issue. It's hard to manage PRs when there are a bunch of ones in there that just need to sit for a while.

**Pull request closed without merging**
