### PR TITLE
Enable caching of ~/.cabal on Travis-CI

### PR DESCRIPTION
**Pull request by avh4**
Enable caching of ~/.cabal on Travis-CI

Depends on #1053

### CODE REVIEW

**Comment by avh4** [comment]
(It is not to me yet whether I am caching the correct directory, and if so whether caching it will actually speed anything up for the build...   Don't merge this until we've verified all that.)

**Comment by laszlopandy** [comment]
I'm not sure if that will cache the modules from elm-compiler too. That
would be a bad thing. We want a clean build each time.

**Comment by avh4** [comment]
This apparently didn't work.  On a subsequent build, Travis reported that it found the cache, but the build look just as long:  either ~/.cabal is not the correct folder to cache, or caching that folder has no effect on `cabal install --only-dependencies --enable-tests`

**Comment by evancz** [comment]
Okay, it sounds like we don't want to do this now, but it'd be excellent if we figure it out someday :)

**Pull request closed without merging**
