### PR TITLE
Expected js output tests

### PR DESCRIPTION
**Pull request by laszlopandy**
This PR extends the "good" and "bad" compiler tests with expected JS tests. These tests compile each Elm file in `good/` and compare it against the corresponding .elm.js file in `good-expected-js/`.

This test has two aims:
1. Make the tests fail if anyone accidentally changes the codegen output.
2. When someone is changing codegen, it forces the author to show the impact of their change in the diff. (If they do not regenerate and commit the good-expected-js files, the test will continue to fail).

The workflow is:
```
$ cabal test
...
Expected JS Tests:
    tests/test-files/good/AliasSubstitution.elm: [OK]
    tests/test-files/good/Lists/EmptyList.elm: [Failed]
Compiled JS did not match expected JS.
  If the change is intentional, rerun the tests with environment variable: ELM_WRITE_NEW_EXPECTED=1
expected: "..."
 but got: "..."

$ ELM_WRITE_NEW_EXPECTED=1 cabal test
...
Expected JS Tests:
    tests/test-files/good/AliasSubstitution.elm: [Failed]
Wrote new expected js: tests/test-files/good-expected-js/AliasSubstitution.elm.js
    tests/test-files/good/Lists/EmptyList.elm: [Failed]
Wrote new expected js: tests/test-files/good-expected-js/Lists/EmptyList.elm.js

$ git commit -a
```

### CODE REVIEW

**Comment by laszlopandy** [comment]
@evancz Even though the compiler is throwing an error right now, I think it is a good idea to merge this PR now because then when your module representation refactor is finished you will be able to see the change in the expected js files. I generated the current set of expected files from last Saturday's master (before the first breaking changes).

**Comment by laszlopandy** [comment]
TODO:
 * Remove where clauses
 * `do` on newline
 * in `case` always put the body on a new line

**Comment by laszlopandy** [comment]
@evancz All comments fixed.

**Comment by evancz** [comment]
Great, LGTM, thanks!

**Pull request merged**
