### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by newtriks**

### CODE REVIEW

**Comment by mgold** [comment]
:+1:

**Comment by evancz** [comment]
Weird! Can you rebase this? It looks fine otherwise. I'm not sure why I'm not allowed to rebase on this website anymore :(

**Comment by jvoigtlaender** [comment]
This has again become out of synch with the master branch.

**Comment by evancz** [comment]
It's fine. I'm going to take a pass through here in the lead up to 0.17 so I'll just sort it out. I don't get notified on "changes to a PR" so I didn't see that it got rebased.

So no worries, this won't be visible to people until they get a fresh link from the compiler, so the earliest it could come out is with 0.17 anyway.

**Comment by evancz** [comment]
Fixed in #1372

**Pull request closed without merging**
