### PR TITLE
Fix ANSI issue everywhere

### PR DESCRIPTION
**Pull request by evancz**
cc @jvoigtlaender

I thought that displayIO was for ANSI and displayS was for not-ANSI. It
turns out that displayS will add the ANSI codes into the string if you
are on not-Windows. This meant that garbage characters were ending up
in the output of JSON errors or reactor errors

@rtfeldman, I’ll try to get a new set of binaries ready for linux
32-bit and mac

### CODE REVIEW

**Comment by rtfeldman** [comment]
:+1:

**Comment by rtfeldman** [comment]
@evancz I assume you mean Windows and 32-bit Linux? Travis has the other binaries covered.

**Comment by evancz** [comment]
I believe Windows is fine because of the particulars of `displayS` where on Windows it already drops things, so I wasn't going to bother.

**Comment by evancz** [comment]
I want to figure out https://github.com/elm-lang/elm-reactor/issues/156 as well though. I am struggling at the moment though :/

**Comment by evancz** [comment]
What do you think about the plan to let it be broken until the new reactor is ready?

**Pull request merged**
