### PR TITLE
Add tests for the parser

### PR DESCRIPTION
**Pull request by avh4**
I wrote this suite of tests while working on elm-format, and thought it would be good to port them over to elm-compiler.  This will allow refactoring of the parser to be done more safely, and will also let me track any subtle syntax changes that happen between versions so that elm-format can be properly updated.

### CODE REVIEW

**Comment by avh4** [comment]
@evancz thoughts on whether you think this is worthwhile?

**Comment by rtfeldman** [comment]
Seems pretty useful right about now, given the recent issues filed about regressions! 😄

cc @evancz

**Comment by mgold** [comment]
Yes! And all of the new parser regressions should be added to the test suite if it doesn't catch them already.

**Comment by avh4** [comment]
Actually, I think this is not what we want to do.  These unit tests that expect on the parsed AST have been extremely brittle and painful to maintain in elm-format.  I think this PR should be dumped, and instead there should be more tests of the type that already exist: having example Elm files, and simply verify that they compile (and/or verify that they produce a specific js output).

**Pull request closed without merging**
